table Dialogue
	lineageTag: 1098757f-2b52-4282-af0f-3893f5a1f749

	column 'Dialogue ID'
		dataType: int64
		formatString: 0
		lineageTag: e2bb160d-1407-4ca9-99c4-ccd617cf3303
		summarizeBy: none
		sourceColumn: Dialogue ID

		annotation SummarizationSetBy = Automatic

	column 'Chapter ID'
		dataType: int64
		formatString: 0
		lineageTag: b7e7a545-2ac4-4bb3-a4e4-b4b51296ccfd
		summarizeBy: none
		sourceColumn: Chapter ID

		annotation SummarizationSetBy = Automatic

	column 'Place ID'
		dataType: int64
		formatString: 0
		lineageTag: 70301c9f-95e6-4b12-b526-5242ae84157d
		summarizeBy: none
		sourceColumn: Place ID

		annotation SummarizationSetBy = Automatic

	column 'Character ID'
		dataType: int64
		formatString: 0
		lineageTag: 86c32df9-a031-413d-97b3-99d1971109d9
		summarizeBy: none
		sourceColumn: Character ID

		annotation SummarizationSetBy = Automatic

	column Dialogue
		dataType: string
		lineageTag: 00eb2313-e8d7-4613-ba78-0c5d66e68cb9
		summarizeBy: none
		sourceColumn: Dialogue

		annotation SummarizationSetBy = Automatic

	column sentiment_score
		dataType: double
		lineageTag: c2ba9f14-42be-44a3-8967-238337d9b309
		summarizeBy: sum
		sourceColumn: sentiment_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sentiment_classification
		dataType: string
		lineageTag: 01b7c3e6-4287-4d38-9091-d8692419a156
		summarizeBy: none
		sourceColumn: sentiment_classification

		annotation SummarizationSetBy = Automatic

	partition Dialogue = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\msava\Documents\Analises de dados\Harry Potter\sentiment_dataframe_com_virgula.csv"),[Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Dialogue ID", Int64.Type}, {"Chapter ID", Int64.Type}, {"Place ID", Int64.Type}, {"Character ID", Int64.Type}, {"Dialogue", type text}, {"sentiment_score", type number}, {"sentiment_classification", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

